### PR TITLE
Make a basic implement for webui plugin

### PR DESCRIPTION
**Pull request by jtydhr88**
hi Stability team,
I am not sure you guys already start to implement the webui plugin or not, but I make a basic version for this big demand.
please let me know how you think about it.

### CODE REVIEW

**Comment by cruhl** [comment]
Hello! 👋

We haven't been able to pick this up yet, so I'd be extremely happy to help you get it finished and merged!

**Comment by cruhl** [comment]
How would you like us to cooperate with you?

Should we create a branch which pulls in from yours, commit directly to yours, etc.?

**Comment by KAJdev** [comment]
@cruhl should be as simple as `gh pr checkout 24`

**Comment by KAJdev** [comment]
Been playing around with this plugin, and so far it seems to work quite well, although with some major issues that need to be addressed before it can be merged:

### issues
- img2img / masking is not implemented
- model/sampler seems to lose its state often
- seed seems to be ignored (not sure if this is webui automatically incrementing seed or not)

### possible implementations:
- history (might be able to implement via https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)
  - can pull from a path in settings
- currently webui needs to be started manually with extra CLI flags.
  - plugin could use path in settings along with a field for extra cli flags to launch webui on startup
  - webui status could replace images generated status

**Comment by cruhl** [comment]
@KAJdev @jtydhr88 @daryllaro Taking a crack at this now

**Comment by merodiro** [comment]
> ### possible implementations:
> * history (might be able to implement via https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)
>   
>   * can pull from a path in settings
> * currently webui needs to be started manually with extra CLI flags.
>   
>   * plugin could use path in settings along with a field for extra cli flags to launch webui on startup

Wouldn't these two implementations work only in case both StableStudio and SD-webui are on the same host and wouldn't support remote webui?

**Comment by merodiro** [comment]
I just tried it with remote sd-webui and it worked well. The only problem I had was that I couldn't load the samplers

**Comment by merodiro** [comment]
image
When I don't choose a model it displays SDXL as the model used for the generation

**Comment by KAJdev** [comment]
I believe this is because internally StableStudio defaults to `stable-diffusion-xl-beta-v2-2-2` as a model ID for input objects. If you aren't returning one it will just use the default object specified in `Generation.Image.Model.StableDiffusionV1.Input.initial`. This can be overridden by providing a default plugin input.

**Comment by cruhl** [comment]
@jtydhr88 We're going to try to get this merged tomorrow, will be updating some code in a bit 👍

**Comment by cruhl** [comment]
@jtydhr88 Are you cool with the README changes I committed? @KAJdev is making some tweaks to the plugin itself and then we're cool to merge. 🦾

**Comment by jtydhr88** [comment]
Yeah! Readme is good for me!

**Comment by KAJdev** [comment]
@jtydhr88 Refactor is going well, noticing some issues with the history plugin. Looks like `get_root_path()` is failing since `__file__` doesn't exist in `exec()`ed python code. `os.getcwd()` should work though.

**Comment by jtydhr88** [comment]
@KAJdev thanks for catching, I will fix it soon

**Review by KAJdev — APPROVED** [review]

**Comment by jtydhr88** [comment]
hi @KAJdev as my test, there is an issue happening on get history image, even webui returns the date, but StableSudio sitll keeps loading without show image:
image
I output the data, and they are all Prmoise:
image
I have to revert your code regarding this part to my previous one.

Another issue is the status keeps on "Ready without history plugin" even the extension already be here and orks well to return date.
image

**Comment by KAJdev** [comment]
Yes, I was having issues with the history plugin, the error mentioned before as well as some possible CORS issues. Will investigate more.

Good catch on the async map there, that revert is fine.

**Comment by jtydhr88** [comment]
besides this issue, anything else needs to do for this init version? or i am good to merge

**Comment by KAJdev** [comment]
I think we are aiming for an early morning merge.

**Comment by cruhl** [comment]
@jtydhr88 Are we good to merge this from your perspective?

**Review by cruhl — APPROVED** [review]

**Comment by SeriousM** [comment]
I really need to thank you @jtydhr88 (@cruhl , @KAJdev ) for bringing this to StableStudio. StableDiffusion now feels so much polished and slick!
Of course there are plenty of opportunities for more features like progress bar/eta, set image size, set settings for variants before dreaming... but this first, very important step was really great work. Well done!

**Pull request merged**
