### PR TITLE
`ComfyUI` plugin

### PR DESCRIPTION
**Pull request by hlky**
Initial ComfyUI plugin implementation

Uses basic workflows for text-to-image, image-to-image, inpaint/outpaint

image

image

msedge_L0mWHAV00N

msedge_qbMLZvzvTt

msedge_lybZfwKaCT

* Image count in UI set to value from plugin, image count != batch size, images are queued, seeds are incremental
* Image strength default value configurable by plugin, also changed the default value because 100% image strength just returns the same image
  * Image strength is backwards to denoise in ComfyUI, e.g. denoise 1.0 is equivalent to Image strength 0%, 75% image strength is equivalent to 0.25 denoise

Note: Plugin UI extension support would be useful for additional features, something like this, just a quick implementation, not pushed for now because it could be done better, maybe the types could be the UI elements in `Theme`, definitions below would change `"select"` -> `"Popout"` and `"boolean"` -> `"Checkbox"`
image
image

TODO: lots

### CODE REVIEW

**Comment by browsertasker3094** [comment]
That is an amazing article.

**Review by kbakdev — APPROVED** [review]

**Comment by cruhl** [comment]
Really awesome work! I’ll be able to help get it merged after the weekend.

**Comment by hlky** [comment]
Let me know if there are any changes or anything to add for this initial version

**Comment by cruhl** [comment]
@hlky We're moving to ComfyUI for lots of things internally now, so it makes sense for this to be a first-party plugin.

Sorry for the whiplash!

Would you mind re-opening this PR? We are interested in having official ComfyUI support by June 22nd and would love to help get this done. 🙏

**Pull request closed without merging**
