### PR TITLE
Sampler

### PR DESCRIPTION
**Pull request by hlky**
image

* add `getStableDiffusionSamplers`
* add `StableDiffusionSampler` - name: string, value: number
  * `value` is for `stablestudio-plugin-stability` e.g. DDIM, 0 - same as proto
  * other plugins will probably just send `sampler.name` directly to the API

Note: If the reason for hardcoding DDIM was for SDXL this will need to be dealt with, either override the value before chainGenerate or override the samplers options when SDXL is selected.

Related issue(s):
#12

### CODE REVIEW

**Comment by cruhl** [comment]
@hlky Thanks a bunch, this is great!

I made a few changes I wanted your feedback on...

- Changed `value` to `id` for `StableDiffusionSampler` since other back-ends might not use proto/Enums
- Added `Generation.Image.Samplers` which manages the samplers list via `react-query` so plugins can potentially return samplers via asynchronous functions

Let me know what you think, this looks really good and I think we can merge when @KAJdev gives a thumbs-up 👍

**Comment by cruhl** [comment]
https://github.com/Stability-AI/StableStudio/issues/20

For when this is merged ^

**Comment by hlky** [comment]
LGTM.

**Review by KAJdev — APPROVED** [review]
LGTM 

Minor nitpick - I might suggest that the sampler names for the stability API plugin be renamed to be more user-friendly (e.g. "K DPM++ SDE" instead of "K_DPMPP_SDE")

**Pull request merged**
